### ISSUE TITLE
Missing isAvailableMethod and missing signed parameter in getPlayer.

### ISSUE THREAD

**Issue by wadim-al** [yandex-games-plugins/cocos#2]
Hi, 

1) isAvailableMethod  is missing in ysdk and shows the following error:
![image](https://github.com/yandex-games-plugins/cocos/assets/29713984/fc3e90e3-bb63-4787-8f48-ebc7e70da708)

2) getPlayer doesn't take the signed parameter.
![image](https://github.com/yandex-games-plugins/cocos/assets/29713984/12411b40-7fb9-4316-8075-48e6830d5500)

This makes this plugin different from official SDK documentation and causes errors displayed in VS code.

**Comment by koteelok** [comment]
Fixed with [1.0.2](https://github.com/yandex-games-plugins/cocos/releases/tag/v1.0.2)
