### ISSUE TITLE
Using plugin in regular web preview causes spamming console with Yandex SDK uncaught errors.

### ISSUE THREAD

**Issue by wadim-al** [yandex-games-plugins/cocos#3]
Hi,

Is there any way not to load the SDK in the regular Cocos Creator web browser preview, but leave the localization portion intact? This causes the following errors:
![image](https://github.com/yandex-games-plugins/cocos/assets/29713984/db76e5bf-e06c-4fe0-b65f-2617f276e83e)

I would like to develop in regular preview, and add SDK calls after the main portion of a game is done. Now I can't do that effectively, because those errors can't be filtered out (I still want to see all errors from Cocos itself), and are messing with my debugging in regular preview in console.

**Comment by koteelok** [comment]
I'm not sure this is a good idea. If we're not using the SDK in preview mode, that means I need to change the type of the ysdk variable to make it nullable.

This will result in repetitive runtime checks for the existence of ysdk throughout your codebase.

I can suggest using the "info", "verbose" or "user messages" sections of the console sidebar to hide these errors.

![image](https://github.com/yandex-games-plugins/cocos/assets/65600719/d5843ef7-94e0-4be4-94d9-346de9a4990e)

**Comment by wadim-al** [comment]
Thanks for the suggestion, but this will hide errors made by me, game engine or 3rd party scripts.

**Comment by koteelok** [comment]
I don't really see a big problem with that, it's not pleasant but it's not terrible.
