### ISSUE TITLE
Не работает плагин

### ISSUE THREAD

**Issue by Atmosaero** [yandex-games-plugins/cocos#5]
После установки в консоль выводит это

![image](https://github.com/yandex-games-plugins/cocos/assets/41229804/d3c30f27-b55c-4ad0-b952-fcf3a5bffc7f)

**Comment by argus-xd** [comment]
Не помню сталкивался ли с этой ошибкой, в readme не описано что нужно установить зависимости 
выглядит так что он не может найти зависимости для расширения 
Нужно зайти через терминал в папку с расширением и выполнить "yarn install" если его нету то погуглить как установить

**Comment by Atmosaero** [comment]
Спасибо, проблема решена!

**Comment by koteelok** [comment]
Устанавливать зависимости через `yarn install` помогает решить проблему, но на самом деле ошибка была на моей стороне, забыл добавить в скрипт сборки несколько зависимостей.

Уже решено с версией [1.0.3](https://github.com/yandex-games-plugins/cocos/releases/).
