### ISSUE TITLE
Error: No parent to post message

### ISSUE THREAD

**Issue by Lex1ch** [yandex-games-plugins/cocos#8]
Здравствуйте. После установки плагина (пробовал установку из zip файла и через ex. manager) и генерации темплейтов, происходит ошибка при запуске preview: 
- Если через браузер, то появляется ошибка - [Browser Preview] Error: No parent to post message. 
- Если через симулятор - просто белый экран.
- Если через редактор - все ок.

Т.к. я привык открывать превью в браузере, то хотел уточнить, нормально ли это?

P/S Также постоянно висит warning - [Assets] Invalid Bundle config ID.

**Comment by koteelok** [comment]
Да, это ожидаемое поведение. К сожалению СДК Яндекс Игр спамит подобными ошибками, если игра запущена не на платформе.

**Comment by koteelok** [comment]
Не совсем понял по поводу белого экрана симулятора, можете скинуть подробнее?

**Comment by Lex1ch** [comment]
> Не совсем понял по поводу белого экрана симулятора, можете скинуть подробнее?

Проверил на разных проектах и это не связано с yandex sdk, скорее дело в самом проекте. Так что спасибо за ответ и успехов в разработке :)
